---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/jrkrish82/pcf-attendee-service-code.git   #<----- REPLACE ME
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: api.system.cumuluslabs.io        #<----- REPLACE ME
    username: krishnaraj.jagannathanrajan@cognizant.com
    password: Source123
    organization: jkrishnaraj-PAL-JUL2    #<----- REPLACE ME
    space: dev         #<----- REPLACE ME
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service
    trigger: true
  - task: test
    file: attendee-service/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: attendee-service
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: attendee-service
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: attendee-service/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: https://attendee-service-ciderlike-antiketogenesis.apps.cumuluslabs.io/attendees 



